# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: check-linting
        name: check-linting
        entry: uv run --frozen --group dev ruff check
        language: system
        types: [file, python]
        stages: [pre-push]
        pass_filenames: false
      - id: check-formatting
        name: check-formatting
        entry: uv run --frozen --group dev ruff format --check
        language: system
        types: [file, python]
        stages: [pre-push]
        pass_filenames: false
      - id: check-typing
        name: check-typing
        entry: uv run --frozen --group dev mypy .
        language: system
        types: [file, python]
        stages: [pre-push]
        pass_filenames: false
      - id: uv-check # `pyproject.toml` と `uv.lock` が整合する
        name: uv-check
        entry: uv lock --check
        language: system
        stages: [pre-push]
        pass_filenames: false
      - id: update-licenses
        name: update-licenses
        entry: uv run --frozen --group dev task update-licenses
        language: system
        stages: [pre-push]
        pass_filenames: false
