# Python 依存パッケージの脆弱性診断を定期的に行う

name: Test Security

on:
  schedule:
    - cron: "00 04 15 * *" # 毎月15日 13:00 JST
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test-security:
    runs-on: ubuntu-22.04
    steps:
      - name: <Setup> Check out the repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: <Setup> Prepare Python Runtime / Python Dependencies
        uses: ./.github/actions/prepare_python
        with:
          dependency-group: dev

      - name: <Setup> Export pylock.toml
        run: |
          uv export --all-groups --no-header -o pylock.toml

      - name: <Test> Check Python dependency security
        # 未リリースの機能を使うためmainブランチのコミットを指定している
        uses: pypa/gh-action-pip-audit@aad10797d60f7c941f2c511ffb70fd81d998c2a2
        with:
          virtual-environment: .venv
          inputs: .
          locked: true
