name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, macos-15-intel, macos-14, ubuntu-22.04]

    steps:
      - name: <Setup> Check out the repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: <Setup> Prepare Python Runtime / Python Dependencies
        uses: ./.github/actions/prepare_python
        with:
          dependency-group: dev

      - name: <Setup> Cache Engine Data
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.local/share/AivisSpeech-Engine
          key: ${{ runner.os }}-${{ runner.arch }}-engine-data

      - name: <Test> Validate uv.lock
        run: |
          uv lock --check
          git diff --exit-code

      - name: <Test> Check linting
        run: PYTHONUTF8=1 uv run ruff check

      - name: <Test> Check formatting
        run: PYTHONUTF8=1 uv run ruff format --check

      - name: <Test> Check typing
        run: uv run task mypy

      - name: <Test> Test codes and coverage
        run: uv run coverage run --omit=test/* -m pytest

      - name: <Deploy> Submit coverage results to Coveralls
        if: runner.os == 'Linux'
        # Coveralls へのアップロードが失敗しても CI は継続させる
        run: uv run coveralls --service=github || echo "::warning::Coveralls failed, but continuing"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: <Test> Check licenses
        run: uv run task check-licenses

      - name: <Test> Test names by checking typo
        if: runner.os == 'Linux'
        run: uv run task typos

  lint-builders:
    runs-on: ubuntu-22.04
    steps:
      - name: <Setup> Check out the repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: <Setup> Install ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: <Test> Check shell files
        run: git ls-files | grep -E '\.(ba)?sh' | xargs shellcheck

      - name: <Test> Check workflow files
        run: |
          bash <(curl -f --retry 3 --retry-delay 5 https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint

      - name: <Test> Check pinact
        uses: suzuki-shunsuke/pinact-action@28aeb220eb3252ad0d4422dd5d9368e925acbd8d # v1.3.0
        with:
          skip_push: "true"
          min_age: "7"
